# -*- coding: utf-8 -*-
"""user_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yhx9v1LvY0SwuU5gpRpn99zFiwBE3hUl
"""

class UserManager:
    def __init__(self):
        self.users = {}

    def add_user(self, user_id, name, email):
        if user_id in self.users:
            raise ValueError("User already exists")
        self.users[user_id] = {"name": name, "email": email}

    def get_user(self, user_id):
        if user_id not in self.users:
            raise ValueError("User not found")
        return self.users[user_id]