# -*- coding: utf-8 -*-
"""test_user_manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYSb8i2gN5rmUHRrdjJdobuKHfopJn6c
"""

import unittest
from unittest.mock import patch
from user_manager import UserManager

class TestUserManager(unittest.TestCase):
    def setUp(self):
        self.manager = UserManager()

    def test_add_user(self):
        # 사용자 추가
        self.manager.add_user(1, "이두원", "두원@example.com")

        # 사용자가 존재하는지 확인
        user = self.manager.get_user(1)
        self.assertEqual(user["name"], "이두원")
        self.assertEqual(user["email"], "두원@example.com")

    def test_get_user(self):
        # 사용자 추가
        self.manager.add_user(2, "홍길동", "길동@example.com")

        # 사용자 가져오기
        user = self.manager.get_user(2)

        # 사용자 정보가 맞는지 확인
        self.assertEqual(user["name"], "홍길동")
        self.assertEqual(user["email"], "길동@example.com")

    def test_get_user_not_found(self):
        # 존재하지 않는 사용자 가져오기 시도
        with self.assertRaises(ValueError):
            self.manager.get_user(100)

    def test_add_existing_user(self):
        # 사용자 추가
        self.manager.add_user(3, "손흥민", "흥민@example.com")

        # 이미 존재하는 사용자를 다시 추가하려고 시도
        with self.assertRaises(ValueError):
            self.manager.add_user(3, "다른 이름", "another@example.com")

if __name__ == '__main__':
    unittest.main()
